package org.myweb.uniplace.domain.ai.domain;

public enum AiIntent {
    GENERAL_QA,
    CONTRACT_RENEWAL_RECOMMEND,
    CONTRACT_ANOMALY_DETECTION,
    ROOM_AVAILABILITY_SEARCH,
    PAYMENT_SUMMARY_DOCUMENT,
    PAYMENT_STATUS_SUMMARY,
    ROOMSERVICE_STOCK_MONITOR,
    COMMON_SPACE_RECOMMEND,
    COMMUNITY_CONTENT_SEARCH,
    COMPLAIN_PRIORITY_CLASSIFY
}
