package org.myweb.uniplace.domain.ai.domain;

public enum AiIntent {
    GENERAL_QA,
    AI_AGENT_CHATBOT,
    VOICE_CHATBOT,
    AI_AGENT_RAG_SEARCH,
    CONTRACT_RENEWAL_RECOMMEND,
    CONTRACT_ANOMALY_DETECTION,
    ROOM_AVAILABILITY_SEARCH,
    PAYMENT_SUMMARY_DOCUMENT,
    PAYMENT_STATUS_SUMMARY,
    ROOMSERVICE_STOCK_MONITOR,
    COMMON_SPACE_RECOMMEND,
    COMMUNITY_CONTENT_SEARCH,
    COMMUNITY_CONTENT_MODERATION,
    PAYMENT_ORDER_SUGGESTION,
    PAYMENT_ORDER_FORM_CREATE,
    COMPLAIN_PRIORITY_CLASSIFY,
    // ✅ 추가
    REVIEW_INFO,
    TOUR_INFO,
    COMPANY_INFO,
    // ✅ 추가
    BUILDING_LIST,
    // ✅ 로그인 유저 전용
    MY_CONTRACT,
    MY_RESERVATION,
    MY_TOUR,
    MY_COMPLAIN,
    // ✅ 어드민 전용
    ADMIN_CHATBOT
}