apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: "/api"
  SERVER_FORWARD_HEADERS_STRATEGY: "framework"
  APP_OAUTH2_REDIRECT_URI: "https://uniplace.site/oauth2/success"
  APP_CORS_ALLOWED_ORIGINS: "https://uniplace.site,https://www.uniplace.site"
  KAKAO_REDIRECT_URI: "https://uniplace.site/api/login/oauth2/code/kakao"
  GOOGLE_REDIRECT_URI: "https://uniplace.site/api/login/oauth2/code/google"
  AI_FASTAPI_BASE_URL: "http://ai-service"
  FILE_UPLOAD_PATH: "./storage/uploads"
  STORAGE_TYPE: "s3"
  AWS_S3_BUCKET: "uniplace-files-194722402714-ap-northeast-2-an"
  AWS_S3_REGION: "ap-northeast-2"
  AWS_S3_BASE_URL: "https://d2pc5j8tpyrzb6.cloudfront.net"
