apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: uniplace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::194722402714:role/uniplace-backend-irsa-s3-files-role
